export const categoryData = [
  {
    name: 'Butter Chicken',
    category: 'Main Course',
    description: 'Delicious creamy chicken curry with a hint of spices.',
    imageId: 'https://via.placeholder.com/400x300.png?text=Butter+Chicken',
    inStock: true,
    isVeg: false,
    price: 250,
    addons: { extraRice: 50, extraGravy: 30 },
    itemAttribute: { spicy: 'medium', servingSize: 'large' },
    ratings: { averageRating: 4.5, reviews: 320 },
    isBestseller: true,
    offerTags: { discount: '10%', validUntil: '2025-12-31' },
    isBolt: false,
    boltImageId: null,
    ribbon: { color: 'green', text: 'Special' },
  },
  {
    name: 'Veg Manchurian',
    category: 'Starter',
    description: 'Crispy fried vegetables tossed in a tangy Chinese sauce.',
    imageId: 'https://via.placeholder.com/400x300.png?text=Veg+Manchurian',
    inStock: true,
    isVeg: true,
    price: 180,
    addons: { extraSauce: 40, extraVeggies: 30 },
    itemAttribute: { spicy: 'high', servingSize: 'medium' },
    ratings: { averageRating: 4.0, reviews: 210 },
    isBestseller: false,
    offerTags: { discount: '5%', validUntil: '2025-05-31' },
    isBolt: false,
    boltImageId: null,
    ribbon: { color: 'red', text: 'Hot' },
  },
  {
    name: 'Cheese Burger',
    category: 'Burger',
    description: 'A juicy beef patty with melted cheese and fresh veggies.',
    imageId: 'https://via.placeholder.com/400x300.png?text=Cheese+Burger',
    inStock: true,
    isVeg: false,
    price: 220,
    addons: { extraCheese: 40, extraBacon: 50 },
    itemAttribute: { spicy: 'low', servingSize: 'large' },
    ratings: { averageRating: 4.2, reviews: 415 },
    isBestseller: true,
    offerTags: { discount: '15%', validUntil: '2025-07-01' },
    isBolt: true,
    boltImageId: 'https://via.placeholder.com/150x150.png?text=Bolt',
    ribbon: { color: 'blue', text: 'Popular' },
  },
  {
    name: 'French Fries',
    category: 'Sides',
    description: 'Crispy golden fries with a sprinkle of salt.',
    imageId: 'https://via.placeholder.com/400x300.png?text=French+Fries',
    inStock: true,
    isVeg: true,
    price: 100,
    addons: { extraSalt: 10, extraKetchup: 15 },
    itemAttribute: { spicy: 'low', servingSize: 'small' },
    ratings: { averageRating: 3.8, reviews: 150 },
    isBestseller: false,
    offerTags: { discount: '2%', validUntil: '2025-04-30' },
    isBolt: false,
    boltImageId: null,
    ribbon: { color: 'yellow', text: 'Snack' },
  },
  {
    name: 'Margherita Pizza',
    category: 'Pizza',
    description: 'Classic pizza topped with fresh mozzarella and basil.',
    imageId: 'https://via.placeholder.com/400x300.png?text=Margherita+Pizza',
    inStock: true,
    isVeg: true,
    price: 300,
    addons: { extraCheese: 50, extraOlives: 30 },
    itemAttribute: { spicy: 'low', servingSize: 'large' },
    ratings: { averageRating: 4.6, reviews: 510 },
    isBestseller: true,
    offerTags: { discount: '20%', validUntil: '2025-06-15' },
    isBolt: false,
    boltImageId: null,
    ribbon: { color: 'green', text: 'Veg Delight' },
  },
  {
    name: 'Pepperoni Pizza',
    category: 'Pizza',
    description: 'A pizza topped with spicy pepperoni and cheese.',
    imageId: 'https://via.placeholder.com/400x300.png?text=Pepperoni+Pizza',
    inStock: true,
    isVeg: false,
    price: 350,
    addons: { extraCheese: 60, extraPepperoni: 40 },
    itemAttribute: { spicy: 'medium', servingSize: 'large' },
    ratings: { averageRating: 4.3, reviews: 440 },
    isBestseller: true,
    offerTags: { discount: '25%', validUntil: '2025-08-31' },
    isBolt: false,
    boltImageId: null,
    ribbon: { color: 'red', text: "Meat Lover's" },
  },
  {
    name: 'Tandoori Chicken',
    category: 'Main Course',
    description: 'Grilled chicken marinated in tandoori spices.',
    imageId: 'https://via.placeholder.com/400x300.png?text=Tandoori+Chicken',
    inStock: true,
    isVeg: false,
    price: 400,
    addons: { extraNaan: 50, extraYogurt: 30 },
    itemAttribute: { spicy: 'high', servingSize: 'medium' },
    ratings: { averageRating: 4.4, reviews: 320 },
    isBestseller: true,
    offerTags: { discount: '15%', validUntil: '2025-09-01' },
    isBolt: false,
    boltImageId: null,
    ribbon: { color: 'orange', text: 'Spicy' },
  },
  {
    name: 'Paneer Tikka',
    category: 'Starter',
    description: 'Marinated paneer grilled to perfection.',
    imageId: 'https://via.placeholder.com/400x300.png?text=Paneer+Tikka',
    inStock: true,
    isVeg: true,
    price: 220,
    addons: { extraPaneer: 40, extraSpices: 25 },
    itemAttribute: { spicy: 'medium', servingSize: 'small' },
    ratings: { averageRating: 4.0, reviews: 210 },
    isBestseller: false,
    offerTags: { discount: '10%', validUntil: '2025-11-30' },
    isBolt: false,
    boltImageId: null,
    ribbon: { color: 'yellow', text: 'Veg Special' },
  },
  {
    name: 'Salmon Sushi',
    category: 'Sushi',
    description: 'Fresh salmon slices over seasoned rice.',
    imageId: 'https://via.placeholder.com/400x300.png?text=Salmon+Sushi',
    inStock: true,
    isVeg: false,
    price: 350,
    addons: { extraWasabi: 30, extraGinger: 20 },
    itemAttribute: { spicy: 'low', servingSize: 'small' },
    ratings: { averageRating: 4.5, reviews: 280 },
    isBestseller: true,
    offerTags: { discount: '10%', validUntil: '2025-09-30' },
    isBolt: false,
    boltImageId: null,
    ribbon: { color: 'pink', text: 'Fresh' },
  },
  {
    name: 'Miso Soup',
    category: 'Soup',
    description: 'Traditional Japanese soup with tofu and seaweed.',
    imageId: 'https://via.placeholder.com/400x300.png?text=Miso+Soup',
    inStock: true,
    isVeg: true,
    price: 120,
    addons: { extraTofu: 20 },
    itemAttribute: { spicy: 'low', servingSize: 'medium' },
    ratings: { averageRating: 4.2, reviews: 150 },
    isBestseller: false,
    offerTags: { discount: '5%', validUntil: '2025-07-31' },
    isBolt: false,
    boltImageId: null,
    ribbon: { color: 'green', text: 'Light' },
  },
  {
    name: 'Beef Tacos',
    category: 'Tacos',
    description: 'Soft tacos filled with spicy beef and fresh toppings.',
    imageId: 'https://via.placeholder.com/400x300.png?text=Beef+Tacos',
    inStock: true,
    isVeg: false,
    price: 280,
    addons: { extraCheese: 40, extraGuacamole: 50 },
    itemAttribute: { spicy: 'high', servingSize: 'medium' },
    ratings: { averageRating: 4.3, reviews: 300 },
    isBestseller: true,
    offerTags: { discount: '20%', validUntil: '2025-10-15' },
    isBolt: false,
    boltImageId: null,
    ribbon: { color: 'red', text: 'Fiery' },
  },
  {
    name: 'Nachos',
    category: 'Sides',
    description: 'Crispy tortilla chips served with cheese and salsa.',
    imageId: 'https://via.placeholder.com/400x300.png?text=Nachos',
    inStock: true,
    isVeg: true,
    price: 200,
    addons: { extraCheese: 40, extraJalapenos: 30 },
    itemAttribute: { spicy: 'medium', servingSize: 'large' },
    ratings: { averageRating: 4.1, reviews: 200 },
    isBestseller: false,
    offerTags: { discount: '10%', validUntil: '2025-06-30' },
    isBolt: false,
    boltImageId: null,
    ribbon: { color: 'yellow', text: 'Crunchy' },
  },
  {
    name: 'Quinoa Salad',
    category: 'Salad',
    description: 'Healthy salad with quinoa, veggies, and vinaigrette.',
    imageId: 'https://via.placeholder.com/400x300.png?text=Quinoa+Salad',
    inStock: true,
    isVeg: true,
    price: 250,
    addons: { extraAvocado: 50 },
    itemAttribute: { spicy: 'low', servingSize: 'medium' },
    ratings: { averageRating: 4.6, reviews: 310 },
    isBestseller: true,
    offerTags: { discount: '15%', validUntil: '2025-12-31' },
    isBolt: false,
    boltImageId: null,
    ribbon: { color: 'green', text: 'Healthy' },
  },
  {
    name: 'Fruit Bowl',
    category: 'Healthy',
    description: 'A refreshing mix of seasonal fruits.',
    imageId: 'https://via.placeholder.com/400x300.png?text=Fruit+Bowl',
    inStock: true,
    isVeg: true,
    price: 200,
    addons: { extraHoney: 20 },
    itemAttribute: { spicy: 'none', servingSize: 'small' },
    ratings: { averageRating: 4.4, reviews: 180 },
    isBestseller: false,
    offerTags: { discount: '10%', validUntil: '2025-08-15' },
    isBolt: false,
    boltImageId: null,
    ribbon: { color: 'pink', text: 'Fresh' },
  },
  {
    name: 'Chicken Biryani',
    category: 'Main Course',
    description: 'Fluffy rice cooked with tender chicken in aromatic spices.',
    imageId: 'https://via.placeholder.com/400x300.png?text=Chicken+Biryani',
    inStock: true,
    isVeg: false,
    price: 300,
    addons: { extraRaita: 30, extraPickle: 20 },
    itemAttribute: { spicy: 'high', servingSize: 'large' },
    ratings: { averageRating: 4.3, reviews: 290 },
    isBestseller: true,
    offerTags: { discount: '5%', validUntil: '2025-05-01' },
    isBolt: false,
    boltImageId: null,
    ribbon: { color: 'brown', text: 'Authentic' },
  },
  {
    name: 'Veg Biryani',
    category: 'Main Course',
    description:
      'Fragrant basmati rice cooked with fresh vegetables and spices.',
    imageId: 'https://via.placeholder.com/400x300.png?text=Veg+Biryani',
    inStock: true,
    isVeg: true,
    price: 250,
    addons: { extraRaita: 20 },
    itemAttribute: { spicy: 'medium', servingSize: 'large' },
    ratings: { averageRating: 4.0, reviews: 200 },
    isBestseller: false,
    offerTags: { discount: '8%', validUntil: '2025-06-30' },
    isBolt: false,
    boltImageId: null,
    ribbon: { color: 'green', text: 'Veg Special' },
  },
];
