export const restaurantData = [
  {
    name: 'The Food House',
    cuisine: ['Indian', 'Chinese'],
    promoted: true,
    rating: 3.5,
    deliveryTime: '30 mins',
    image: 'https://picsum.photos/400/300?random=1',
    menu: [
      { name: 'Butter Chicken', price: 250, category: 'Main Course' },
      { name: 'Veg Manchurian', price: 180, category: 'Starter' },
    ],
  },
  {
    name: 'Burger Hub',
    cuisine: ['American', 'Fast Food'],
    promoted: false,
    rating: 3.2,
    deliveryTime: '25 mins',
    image: 'https://picsum.photos/400x300?text=Tandoori+Treats',
    menu: [
      { name: 'Cheese Burger', price: 220, category: 'Burger' },
      { name: 'French Fries', price: 100, category: 'Sides' },
    ],
  },
  {
    name: 'Pizza Paradise',
    cuisine: ['Italian', 'Pizza'],
    promoted: true,
    rating: 4.7,
    deliveryTime: '40 mins',
    image: 'https://picsum.photos/400/300?random=2',
    menu: [
      { name: 'Margherita Pizza', price: 300, category: 'Pizza' },
      { name: 'Pepperoni Pizza', price: 350, category: 'Pizza' },
    ],
  },
  {
    name: 'Tandoori Treats',
    cuisine: ['Indian', 'Mughlai'],
    promoted: false,
    rating: 3.6,
    deliveryTime: '35 mins',
    image: 'https://via.placeholder.com/400x300.png?text=Tandoori+Treats',
    menu: [
      { name: 'Tandoori Chicken', price: 400, category: 'Main Course' },
      { name: 'Paneer Tikka', price: 220, category: 'Starter' },
    ],
  },
  {
    name: 'Sushi Delight',
    cuisine: ['Japanese', 'Sushi'],
    promoted: false,
    rating: 3.8,
    deliveryTime: '45 mins',
    image: 'https://picsum.photos/400/300?random=3',
    menu: [
      { name: 'Salmon Sushi', price: 350, category: 'Sushi' },
      { name: 'Miso Soup', price: 120, category: 'Soup' },
    ],
  },
  {
    name: 'Taco Fiesta',
    cuisine: ['Mexican', 'Tacos'],
    promoted: false,
    rating: 4.3,
    deliveryTime: '20 mins',
    image: 'https://via.placeholder.com/400x300.png?text=Taco+Fiesta',
    menu: [
      { name: 'Beef Tacos', price: 280, category: 'Tacos' },
      { name: 'Nachos', price: 200, category: 'Sides' },
    ],
  },
  {
    name: 'Healthy Bites',
    cuisine: ['Salads', 'Healthy'],
    promoted: false,
    rating: 4.5,
    deliveryTime: '30 mins',
    image: 'https://picsum.photos/400/300?random=4',
    menu: [
      { name: 'Quinoa Salad', price: 250, category: 'Salad' },
      { name: 'Fruit Bowl', price: 200, category: 'Healthy' },
    ],
  },
  {
    name: 'Biryani Bliss',
    cuisine: ['Indian', 'Biryani'],
    promoted: false,
    rating: 3.9,
    deliveryTime: '50 mins',
    image: 'https://via.placeholder.com/400x300.png?text=Biryani+Bliss',
    menu: [
      { name: 'Chicken Biryani', price: 300, category: 'Main Course' },
      { name: 'Veg Biryani', price: 250, category: 'Main Course' },
    ],
  },
  {
    name: 'Pasta Heaven',
    cuisine: ['Italian', 'Pasta'],
    promoted: false,
    rating: 4.4,
    deliveryTime: '28 mins',
    image: 'https://picsum.photos/400/300?text=Pasta+Heaven',
    menu: [
      { name: 'Penne Alfredo', price: 260, category: 'Pasta' },
      { name: 'Garlic Bread', price: 120, category: 'Sides' },
    ],
  },
  {
    name: 'Kebab Kingdom',
    cuisine: ['Middle Eastern', 'Kebabs'],
    promoted: false,
    rating: 3.7,
    deliveryTime: '38 mins',
    image: 'https://via.placeholder.com/400x300.png?text=Kebab+Kingdom',
    menu: [
      { name: 'Lamb Kebabs', price: 400, category: 'Main Course' },
      { name: 'Hummus & Pita', price: 180, category: 'Starter' },
    ],
  },
  {
    name: 'Dessert Haven',
    cuisine: ['Desserts', 'Bakery'],
    promoted: false,
    rating: 2.6,
    deliveryTime: '15 mins',
    image: 'https://picsum.photos/400/300?random=6',
    menu: [
      { name: 'Chocolate Cake', price: 150, category: 'Dessert' },
      { name: 'Cheesecake', price: 200, category: 'Dessert' },
    ],
  },
];
