export const restaurantData = [
  {
    name: 'The Food House',
    cuisine: ['Indian', 'Chinese'],
    promoted: true,
    rating: 3.5,
    deliveryTime: '30 mins',
    image: 'https://picsum.photos/400/300?random=1',
    menu: [
      {
        name: 'Butter Chicken',
        price: 250,
        category: 'Main Course',
        description: 'Delicious creamy chicken curry with a hint of spices.',
        imageId: 'https://via.placeholder.com/400x300.png?text=Butter+Chicken',
        inStock: true,
        isVeg: false,
        addons: { extraRice: 50, extraGravy: 30 },
        itemAttribute: { spicy: 'medium', servingSize: 'large' },
        ratings: { averageRating: 4.5, reviews: 320 },
        isBestseller: true,
        offerTags: { discount: '10%', validUntil: '2025-12-31' },
        isBolt: false,
        boltImageId: null,
        ribbon: { color: 'green', text: 'Special' },
      },
      {
        name: 'Veg Manchurian',
        price: 180,
        category: 'Starter',
        description: 'Crispy fried vegetables tossed in a tangy Chinese sauce.',
        imageId: 'https://via.placeholder.com/400x300.png?text=Veg+Manchurian',
        inStock: true,
        isVeg: true,
        addons: { extraSauce: 40, extraVeggies: 30 },
        itemAttribute: { spicy: 'high', servingSize: 'medium' },
        ratings: { averageRating: 4.0, reviews: 210 },
        isBestseller: false,
        offerTags: { discount: '5%', validUntil: '2025-05-31' },
        isBolt: false,
        boltImageId: null,
        ribbon: { color: 'red', text: 'Hot' },
      },
    ],
  },
  {
    name: 'Burger Hub',
    cuisine: ['American', 'Fast Food'],
    promoted: false,
    rating: 3.2,
    deliveryTime: '25 mins',
    image: 'https://picsum.photos/400x300?text=Tandoori+Treats',
    menu: [
      {
        name: 'Cheese Burger',
        price: 220,
        category: 'Burger',
        description: 'A juicy beef patty with melted cheese and fresh veggies.',
        imageId: 'https://via.placeholder.com/400x300.png?text=Cheese+Burger',
        inStock: true,
        isVeg: false,
        addons: { extraCheese: 40, extraBacon: 50 },
        itemAttribute: { spicy: 'low', servingSize: 'large' },
        ratings: { averageRating: 4.2, reviews: 415 },
        isBestseller: true,
        offerTags: { discount: '15%', validUntil: '2025-07-01' },
        isBolt: true,
        boltImageId: 'https://via.placeholder.com/150x150.png?text=Bolt',
        ribbon: { color: 'blue', text: 'Popular' },
      },
      {
        name: 'French Fries',
        price: 100,
        category: 'Sides',
        description: 'Crispy golden fries with a sprinkle of salt.',
        imageId: 'https://via.placeholder.com/400x300.png?text=French+Fries',
        inStock: true,
        isVeg: true,
        addons: { extraSalt: 10, extraKetchup: 15 },
        itemAttribute: { spicy: 'low', servingSize: 'small' },
        ratings: { averageRating: 3.8, reviews: 150 },
        isBestseller: false,
        offerTags: { discount: '2%', validUntil: '2025-04-30' },
        isBolt: false,
        boltImageId: null,
        ribbon: { color: 'yellow', text: 'Snack' },
      },
    ],
  },
  {
    name: 'Pizza Paradise',
    cuisine: ['Italian', 'Pizza'],
    promoted: true,
    rating: 4.7,
    deliveryTime: '40 mins',
    image: 'https://picsum.photos/400/300?random=2',
    menu: [
      {
        name: 'Margherita Pizza',
        price: 300,
        category: 'Pizza',
        description: 'Classic pizza topped with fresh mozzarella and basil.',
        imageId:
          'https://via.placeholder.com/400x300.png?text=Margherita+Pizza',
        inStock: true,
        isVeg: true,
        addons: { extraCheese: 50, extraOlives: 30 },
        itemAttribute: { spicy: 'low', servingSize: 'large' },
        ratings: { averageRating: 4.6, reviews: 510 },
        isBestseller: true,
        offerTags: { discount: '20%', validUntil: '2025-06-15' },
        isBolt: false,
        boltImageId: null,
        ribbon: { color: 'green', text: 'Veg Delight' },
      },
      {
        name: 'Pepperoni Pizza',
        price: 350,
        category: 'Pizza',
        description: 'A pizza topped with spicy pepperoni and cheese.',
        imageId: 'https://via.placeholder.com/400x300.png?text=Pepperoni+Pizza',
        inStock: true,
        isVeg: false,
        addons: { extraCheese: 60, extraPepperoni: 40 },
        itemAttribute: { spicy: 'medium', servingSize: 'large' },
        ratings: { averageRating: 4.3, reviews: 440 },
        isBestseller: true,
        offerTags: { discount: '25%', validUntil: '2025-08-31' },
        isBolt: false,
        boltImageId: null,
        ribbon: { color: 'red', text: "Meat Lover's" },
      },
    ],
  },
  {
    name: 'Tandoori Treats',
    cuisine: ['Indian', 'Mughlai'],
    promoted: false,
    rating: 3.6,
    deliveryTime: '35 mins',
    image: 'https://via.placeholder.com/400x300.png?text=Tandoori+Treats',
    menu: [
      {
        name: 'Tandoori Chicken',
        price: 400,
        category: 'Main Course',
        description: 'Grilled chicken marinated in tandoori spices.',
        imageId:
          'https://via.placeholder.com/400x300.png?text=Tandoori+Chicken',
        inStock: true,
        isVeg: false,
        addons: { extraNaan: 50, extraYogurt: 30 },
        itemAttribute: { spicy: 'high', servingSize: 'medium' },
        ratings: { averageRating: 4.4, reviews: 320 },
        isBestseller: true,
        offerTags: { discount: '15%', validUntil: '2025-09-01' },
        isBolt: false,
        boltImageId: null,
        ribbon: { color: 'orange', text: 'Spicy' },
      },
      {
        name: 'Paneer Tikka',
        price: 220,
        category: 'Starter',
        description: 'Marinated paneer grilled to perfection.',
        imageId: 'https://via.placeholder.com/400x300.png?text=Paneer+Tikka',
        inStock: true,
        isVeg: true,
        addons: { extraPaneer: 40, extraSpices: 25 },
        itemAttribute: { spicy: 'medium', servingSize: 'small' },
        ratings: { averageRating: 4.0, reviews: 210 },
        isBestseller: false,
        offerTags: { discount: '10%', validUntil: '2025-11-30' },
        isBolt: false,
        boltImageId: null,
        ribbon: { color: 'yellow', text: 'Veg Special' },
      },
    ],
  },
];
